#!/usr/bin/env python3
# theilsen-build-margins.py -- generate a harness that PRINTS the numeric
# margin at every assertion site in test-theilsen.praat.
#
# A suite that reports 47/47 PASS proves the assertions did not fire. It does
# not report how close any of them came to firing. This tool parses the suite,
# lifts its vectors, its include lines and its expected literals VERBATIM (no
# retyping -- transcription is the defect class this whole work item exists to
# close), and emits _margins_generated.praat, which recomputes each assertion
# as `d = abs (actual - (expected literal))` and prints d alongside the
# tolerance in force.
#
# The generated harness is written into dev/tests/phase2/ so the suite's own
# relative include paths resolve unchanged.
#
# Paths resolve from this file's location.
#
#!/usr/bin/env python3
# Build a margin-measurement harness FROM test-theilsen.praat by parsing it.
#
# The previous attempt at this measurement hand-transcribed the suite's test
# vectors into a harness and reported diffs of 0.5 / 0.104 / 0.0043 against a
# 5e-11 tolerance on a suite that had just passed 47/47 -- i.e. the harness was
# measuring different data. Transcription is the exact defect class this whole
# work item exists to close, so the harness is now GENERATED from the file.
#
# Nothing here retypes a vector or an expected literal. The expected literal is
# spliced verbatim into a Praat expression `abs(actual - <literal>)`, so the
# comparison is against the same characters the suite asserts.

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PLUGIN = os.path.abspath(os.path.join(HERE, "..", ".."))
PHASE2 = os.path.join(PLUGIN, "dev", "tests", "phase2")
SRC = os.path.join(PHASE2, "test-theilsen.praat")

raw = open(SRC).read().split("\n")

# --- join Praat "..." continuation lines into logical lines -----------------
logical = []
for line in raw:
    s = line.strip()
    if s.startswith("..."):
        if not logical:
            sys.exit("continuation before any line")
        logical[-1] = logical[-1] + " " + s[3:].strip()
    else:
        logical.append(line.rstrip())

# --- vectors ---------------------------------------------------------------
vec_re = re.compile(r"^\s*(\w+)#\s*=\s*\{([^}]*)\}\s*$")
vectors = {}
for line in logical:
    m = vec_re.match(line)
    if m:
        vectors[m.group(1)] = [v.strip() for v in m.group(2).split(",")]

# --- assertions ------------------------------------------------------------
# @emlTestAssertEqualNum: "name", <expected>, emlTheilSen.<field>, <tol>
asrt_re = re.compile(
    r'^\s*@emlTestAssertEqualNum:\s*"([^"]*)"\s*,\s*(.+?)\s*,\s*'
    r'emlTheilSen\.(\w+)\s*,\s*(\w+)\s*$')
# the @emlTheilSen call that most recently preceded each assertion
call_re = re.compile(r"^\s*@emlTheilSen:\s*(\w+)#\s*,\s*(\w+)#\s*$")

tol_re = re.compile(r"^\s*(ts\w*[Tt]ol\w*|tsExact)\s*=\s*(\S+)\s*$")
tolerances = {}
for line in logical:
    m = tol_re.match(line)
    if m:
        tolerances[m.group(1)] = m.group(2)

cur = None
rows = []
for line in logical:
    m = call_re.match(line)
    if m:
        cur = (m.group(1), m.group(2))
        continue
    m = asrt_re.match(line)
    if m:
        name, expected, field, tol = m.groups()
        if cur is None:
            sys.exit("assertion before any @emlTheilSen call: " + name)
        rows.append(dict(name=name, expected=expected, field=field,
                         tol=tol, xv=cur[0], yv=cur[1]))

if not rows:
    sys.exit("parsed no assertions -- the parser is broken, not the suite")

# --- emit the Praat harness ------------------------------------------------
out = []
out.append("# GENERATED by build_margins.py from test-theilsen.praat.")
out.append("# Do not edit; do not commit. Prints |actual - expected| per site.")
# The harness is WRITTEN INTO the phase2 directory (same directory as the
# suite it was generated from) so the suite's own relative include paths
# resolve identically. The include lines below are not retyped either --
# they are lifted verbatim from the suite, minus the test-helpers include
# (the harness asserts nothing; it only prints differences).
for line in logical:
    s = line.strip()
    if s.startswith("include ") and "eml-test-helpers" not in s:
        out.append(s)
out.append("writeInfoLine: \"MARGINS\"")
for v, vals in vectors.items():
    out.append("%s# = { %s }" % (v, ", ".join(vals)))

lastcall = None
for r in rows:
    call = (r["xv"], r["yv"])
    if call != lastcall:
        out.append("@emlTheilSen: %s#, %s#" % call)
        lastcall = call
    out.append("d = abs (emlTheilSen.%s - (%s))" % (r["field"], r["expected"]))
    out.append('appendInfoLine: "%s|", string$ (d)' % r["name"])

DEST = (PHASE2 + "/"
        "_margins_generated.praat")
open(DEST, "w").write("\n".join(out) + "\n")

# --- and a manifest for the comparison side --------------------------------
import json
json.dump(dict(rows=rows, tolerances=tolerances),
          open(os.path.join(HERE, "theilsen_margin_rows.json"), "w"), indent=1)

print("parsed %d vectors, %d numeric assertion sites, tolerances %s"
      % (len(vectors), len(rows), tolerances))
for r in rows:
    print("  %-42s %-22s tol=%s" % (r["name"], r["expected"], r["tol"]))
