# ============================================================================
# EML Praat Tools — Quick Start Guide
# ============================================================================
# Prints a quick-start guide to the Info window.
# ============================================================================

writeInfoLine: "============================================================"
appendInfoLine: "  EML Praat Tools — Quick Start Guide"
appendInfoLine: "============================================================"
appendInfoLine: ""
appendInfoLine: "TWO WAYS TO USE EML TOOLS"
appendInfoLine: ""
appendInfoLine: "  1. MENU ITEMS (no scripting)"
appendInfoLine: "     Select a Table in the object list, then click one of"
appendInfoLine: "     the EML: action buttons. Fill in the dialog. Results"
appendInfoLine: "     appear in this Info window."
appendInfoLine: ""
appendInfoLine: "  2. IN YOUR OWN SCRIPTS"
appendInfoLine: "     Add these includes at the top of your script:"
appendInfoLine: ""
appendInfoLine: "       include plugin_EML_Praat_Tools/stats/eml-core-utilities.praat"
appendInfoLine: "       include plugin_EML_Praat_Tools/stats/eml-core-descriptive.praat"
appendInfoLine: "       include plugin_EML_Praat_Tools/stats/eml-extract.praat"
appendInfoLine: "       include plugin_EML_Praat_Tools/stats/eml-output.praat"
appendInfoLine: "       include plugin_EML_Praat_Tools/stats/eml-inferential.praat"
appendInfoLine: ""
appendInfoLine: "     Then call procedures directly. Example:"
appendInfoLine: ""
appendInfoLine: "       group1# = {195, 210, 188, 203, 197}"
appendInfoLine: "       group2# = {165, 172, 158, 180, 163}"
appendInfoLine: "       @emlTTest: group1#, group2#, 2, 0"
appendInfoLine: "       @emlFormatP: emlTTest.p"
appendInfoLine: "       appendInfoLine: fixed$(emlTTest.t, 2)"
appendInfoLine: ""
appendInfoLine: "------------------------------------------------------------"
appendInfoLine: "  AVAILABLE TESTS"
appendInfoLine: "------------------------------------------------------------"
appendInfoLine: ""
appendInfoLine: "  Descriptive:   @emlDescribe"
appendInfoLine: "  Two-group:     @emlTTest, @emlTTestPaired"
appendInfoLine: "                 @emlMannWhitneyU, @emlWilcoxonSignedRank"
appendInfoLine: "  Effect sizes:  @emlCohenD, @emlRankBiserialR,"
appendInfoLine: "                 @emlMatchedPairsR"
appendInfoLine: "  Correlation:   @emlPearsonCorrelation,"
appendInfoLine: "                 @emlSpearmanCorrelation"
appendInfoLine: "  k-group:       @emlOneWayAnova, @emlTwoWayAnova,"
appendInfoLine: "                 @emlKruskalWallis"
appendInfoLine: "  Post-hoc:      @emlTukeyHSD, @emlPairwiseT,"
appendInfoLine: "                 @emlPairwiseWilcoxon, @emlDunnTest,"
appendInfoLine: "                 @emlScheffe"
appendInfoLine: "  p-adjustment:  @emlBonferroni, @emlHolm,"
appendInfoLine: "                 @emlBenjaminiHochberg"
appendInfoLine: ""
appendInfoLine: "------------------------------------------------------------"
appendInfoLine: "  DOCUMENTATION"
appendInfoLine: "------------------------------------------------------------"
appendInfoLine: ""
appendInfoLine: "  Full reference:  docs/procedure-reference.md"
appendInfoLine: "  Copy-paste code: docs/recipes.md"
appendInfoLine: "  Demo figure:     Run Stats Demo (in EML Tools menu)"
appendInfoLine: ""
appendInfoLine: "  Both files are in the plugin_EML_Praat_Tools folder inside"
appendInfoLine: "  your Praat preferences directory."
appendInfoLine: ""
appendInfoLine: "============================================================"
appendInfoLine: "  Framework: Ian Howell, Embodied Music Lab"
appendInfoLine: "  www.embodiedmusiclab.com"
appendInfoLine: "============================================================"
