#!/usr/bin/env Rscript
# ============================================================================
# v161 -- Table S2 is GENERATED from the registry, and stays that way
# ============================================================================
# Ian Howell -- Embodied Music Lab -- GPL-3.0-or-later
#
# WHAT THIS CLOSES. RULING_PUBLIC_SURFACE_2026-09-01.md's mechanism item 3:
# "docs, the barrel, and Table S2 are GENERATED from the registry and a text
# check asserts the generated artifacts match it (single source, v105
# pattern)." validate/v155_public_registry.R's own generation check attested
# the gap honestly rather than passing vacuously: "Table S2 generated from
# REGISTRY.tsv: NOT WIRED, AND NO SUCH FILE EXISTS." This file is the text
# check that ruling asked for, for the Table S2 third of that item --
# CLAIMS_EVIDENCE_LEDGER_2026-09-02.md row 11.
#
# The generator is walkthrough/kit/build_table_s2.py, following the shape
# walkthrough/kit/build_coverage_map.py already established for a sibling
# per-registry-row table (same read function, same imported kind
# classifier -- see that script's docstring). This file does not re-derive
# Table S2's content: it RUNS the generator fresh and requires the bytes it
# prints to be the bytes committed at walkthrough/kit/table_s2.tsv. Whichever
# of the two a future edit touches -- REGISTRY.tsv, the generator, or the
# committed file -- and forgets the other two, this fails, so the three
# cannot drift apart silently.
#
# THE ROW COUNT IS READ, NOT ASSERTED. NOTE_NAMES_ACCEPTED_2026-09-01.md
# fixes Table S2 at 42 rows once the mixed-model row's ordered exclusion
# (RULING_REGISTRY_VERDICTS_2026-09-01.md #1) executes in REGISTRY.tsv; that
# removal has not executed as of this file (REGISTRY.tsv's own header still
# says "43 rows"). Section 2 below cross-checks Table S2's row count against
# REGISTRY.tsv's own data-row count, computed independently by this file
# rather than copied from either script, so the two numbers this ledger row
# has cited (42 and 43) both pass this check on the day they are true and
# neither is hardcoded here.
#
# WHAT THIS DOES NOT CLOSE. The barrel third of mechanism item 3
# (plugin_EML_StatsGraphs/scripts/eml-lib-user.praat, generated by
# setup.praat from its own hand-kept module list, not from REGISTRY.tsv) and
# the docs third are both untouched -- see build_table_s2.py's own
# docstring and CLAIMS_EVIDENCE_LEDGER_2026-09-02.md row 11 for what
# remains.
#
#     Rscript validate/v161_table_s2_generation.R
#
# Input: plugin_EML_StatsGraphs/REGISTRY.tsv, walkthrough/kit/build_table_s2.py
#        and walkthrough/kit/table_s2.tsv. python3 on PATH; no Praat.
#
# ATTRIBUTION
# Framework: EML PraatGen by Ian Howell
#            Embodied Music Lab -- www.embodiedmusiclab.com
# Code generation: Claude (Anthropic)
# Script author: Ian Howell -- created and verified by this individual
# ============================================================================

V <- "v161"

if (!exists("eml_report")) {
    .a <- commandArgs(FALSE); .f <- sub("^--file=", "", .a[grep("^--file=", .a)])
    source(file.path(if (length(.f)) dirname(normalizePath(.f)) else ".", "helpers.R"))
}

ROOT <- repo_path(".")
GENERATOR <- repo_path("walkthrough", "kit", "build_table_s2.py")
COMMITTED <- repo_path("walkthrough", "kit", "table_s2.tsv")
REGISTRY <- repo_path("plugin_EML_StatsGraphs", "REGISTRY.tsv")

check_true(V, "the generator script exists", file.exists(GENERATOR))
check_true(V, "the committed table exists", file.exists(COMMITTED))
check_true(V, "REGISTRY.tsv exists", file.exists(REGISTRY))

py <- Sys.which("python3")
have_py <- nzchar(py)
check_true(V, "python3 is available (the generator is a python script)",
           have_py)

# ---------------------------------------------------------------------------
# 1. THE COMMITTED FILE IS EXACTLY WHAT THE GENERATOR EMITS, TODAY
# ---------------------------------------------------------------------------
# Run fresh, from the repo root -- the generator resolves REGISTRY.tsv
# relative to the working directory, matching build_coverage_map.py's own
# convention (see that script's docstring). Compared line for line, not
# just row-for-row: a header-comment or column-order change is exactly the
# kind of drift this check exists to catch, same as a data change.
generated <- character(0)
gen_status <- NA_integer_
if (have_py && file.exists(GENERATOR)) {
    old <- setwd(ROOT); on.exit(setwd(old), add = TRUE)
    out <- suppressWarnings(system2(py, GENERATOR, stdout = TRUE, stderr = FALSE))
    gen_status <- attr(out, "status")
    if (is.null(gen_status)) gen_status <- 0L
    generated <- out
}
check_true(V, "the generator runs cleanly (exit 0)",
           have_py && identical(as.integer(gen_status), 0L))

committed <- if (file.exists(COMMITTED)) readLines(COMMITTED, warn = FALSE) else character(0)
check_true(V,
           sprintf("table_s2.tsv is byte-identical to the generator's current output (%d lines generated, %d lines committed)",
                    length(generated), length(committed)),
           have_py && identical(generated, committed))

# ---------------------------------------------------------------------------
# 2. THE ROW COUNT AGREES WITH REGISTRY.tsv, WHATEVER THAT COUNT IS TODAY
# ---------------------------------------------------------------------------
# Computed independently of build_table_s2.py's own count -- a bug shared by
# the generator and this check would not be caught by section 1 alone, since
# section 1 only asks whether the committed file matches what the generator
# (rightly or wrongly) produces. This counts REGISTRY.tsv's own data rows
# by the same rule REGISTRY.tsv's header documents for itself: skip blank
# lines and lines starting with "#", and the first surviving line is the
# column header, not data.
reg_lines <- if (file.exists(REGISTRY)) readLines(REGISTRY, warn = FALSE) else character(0)
reg_data <- reg_lines[nzchar(trimws(reg_lines)) & !grepl("^#", reg_lines)]
n_registry_rows <- max(0L, length(reg_data) - 1L)  # minus the "name\tfile\t..." header

table_data <- committed[nzchar(trimws(committed)) & !grepl("^#", committed)]
n_table_rows <- max(0L, length(table_data) - 1L)  # minus "registry_name\tkind\tdescription"

check_true(V,
           sprintf("Table S2 has one row per REGISTRY.tsv row (registry: %d, table: %d)",
                    n_registry_rows, n_table_rows),
           n_registry_rows > 0 && n_registry_rows == n_table_rows)

# Informational only -- neither 42 nor 43 gates this file; see the header
# comment above for why. Reported so a reader can see which state the
# repository is in without opening REGISTRY.tsv.
cat(sprintf("\n  registry / Table S2 row count today: %d\n", n_registry_rows))
if (n_registry_rows == 42L) {
    cat("  (42 -- the settlement wave's LMM exclusion has executed)\n")
} else if (n_registry_rows == 43L) {
    cat("  (43 -- pre-settlement; the mixed-model row is still present)\n")
} else {
    cat("  (neither 42 nor 43 -- a registry row was added or removed for a\n")
    cat("   different reason; this check does not care which, only that\n")
    cat("   Table S2 tracks it)\n")
}

# ---------------------------------------------------------------------------
# 3. SCHEMA -- EVERY DATA ROW HAS THE THREE COLUMNS, NONE BLANK, KIND KNOWN
# ---------------------------------------------------------------------------
KNOWN_KINDS <- c("analysis", "drawing", "utility")
if (length(table_data) >= 1) {
    header <- table_data[1]
    body <- if (length(table_data) > 1) table_data[-1] else character(0)
    check_true(V, "the header row is the expected three columns",
               identical(header, "registry_name\tkind\tdescription"))

    split3 <- strsplit(body, "\t", fixed = TRUE)
    wrong_n <- which(vapply(split3, length, integer(1)) != 3L)
    check_true(V, "every data row has exactly three tab-separated fields",
               length(wrong_n) == 0)

    if (length(wrong_n) == 0 && length(split3)) {
        names_col <- vapply(split3, `[`, character(1), 1)
        kinds_col <- vapply(split3, `[`, character(1), 2)
        desc_col  <- vapply(split3, `[`, character(1), 3)

        check_true(V, "no registry_name is blank", all(nzchar(names_col)))
        check_true(V, "no description is blank", all(nzchar(desc_col)))
        check_true(V, "every registry_name is unique (one row per procedure)",
                   !any(duplicated(names_col)))
        bad_kind <- setdiff(unique(kinds_col), KNOWN_KINDS)
        check_true(V,
                   sprintf("every kind is one of analysis/drawing/utility (%s)",
                           if (length(bad_kind)) paste(bad_kind, collapse = ", ") else "none unrecognised"),
                   length(bad_kind) == 0)
    }
}

if (!exists("EML_SUITE")) { eml_report("v161 -- Table S2 generation"); eml_exit() }
