# ============================================================================
# v16 — CSV export: the tidy long format
#
# Ian Howell — Embodied Music Lab — GPL-3.0-or-later
#
# The old export was a fixed 20-column wide schema made to carry every test
# in the plugin. It failed in fourteen findings for three structural reasons:
# no way to say "not applicable" (so every caller passed 0, and the one-way
# omnibus row ended in eight zeros indistinguishable from measurements);
# slots reused for unrelated quantities (regression wrote its slope into
# mean1 and its intercept into median1); and nowhere to put a second df, an
# SS, an MS or a confidence interval, so F(1,28) exported as df=1.00 and the
# ANOVA table could not be reconstructed.
#
# This script exists because a file whose numbers cannot be recovered is not
# an export. It reads the committed exports under evidence/csv_export/ —
# generated by harness/probes/csv_export_drive.praat from the live library —
# and checks every value against R.
#
# THE STRUCTURAL CHECKS AT THE FOOT ARE THE POINT. Any single number can be
# right in a broken schema. What the old format could not do was survive
# being read back: those checks assert that it now can, and that no zero
# anywhere in the output means "not applicable".
# ============================================================================

if (!exists("eml_report")) {
    .a <- commandArgs(FALSE); .f <- sub("^--file=", "", .a[grep("^--file=", .a)])
    source(file.path(if (length(.f)) dirname(normalizePath(.f)) else ".", "helpers.R"))
}

csvdir <- repo_path("evidence", "csv_export")
.cache <- new.env()
csv_of <- function(f) {
    if (is.null(.cache[[f]])) {
        p <- file.path(csvdir, f)
        if (!file.exists(p)) stop(sprintf("missing export: %s", p))
        .cache[[f]] <- read.csv(p, stringsAsFactors = FALSE)
    }
    .cache[[f]]
}
# Fails loudly on a missing field rather than returning NA, for the same
# reason every other accessor in this suite does: a silent NA turns a
# regression into a pass.
field <- function(f, analysis, term, name) {
    d <- csv_of(f)
    v <- d$value[d$analysis == analysis & d$term == term & d$field == name]
    if (!length(v)) {
        stop(sprintf("no row in %s for analysis='%s' term='%s' field='%s'",
                     f, analysis, term, name))
    }
    if (length(v) > 1) {
        stop(sprintf("%d rows in %s for '%s'/'%s'/'%s'; expected 1",
                     length(v), f, analysis, term, name))
    }
    suppressWarnings(as.numeric(v[1]))
}
has_field <- function(f, analysis, term, name) {
    d <- csv_of(f)
    any(d$analysis == analysis & d$term == term & d$field == name)
}

# --- the inputs, reconstructed exactly as the drive script built them ------
g_idx  <- ((1:15 - 1) %% 3) + 1
anova_y   <- c(92, 88, 85)[g_idx] + ((1:15) %% 5) * 1.3
anova_grp <- factor(c("Soprano", "Mezzo", "Alto")[g_idx])
px <- c(2, 3, 5, 6, 8, 9, 11, 12, 14, 15, 17, 18)
py <- c(61, 63, 66, 68, 72, 74, 78, 80, 84, 85, 89, 91)
tg <- c(71.2, 73.5, 70.8, 74.1, 72.6, 75.0, 71.9, 73.3,
        64.5, 66.1, 63.8, 67.2, 65.4, 66.9, 64.2, 65.8)
sop <- tg[1:8]; alt <- tg[9:16]
pre  <- c(1.42, 1.61, 1.33, 1.75, 1.58, 1.49, 1.66, 1.38, 1.71, 1.55)
post <- c(1.21, 1.35, 1.18, 1.44, 1.29, 1.26, 1.41, 1.15, 1.48, 1.31)

# --- one-way ANOVA --------------------------------------------------------
s <- summary(aov(anova_y ~ anova_grp))[[1]]
A <- "One-way ANOVA"
check("v16", "ANOVA F",   field("anova.csv", A, "", "F"),   s[1, "F value"], tol = 5e-9)
check("v16", "ANOVA p",   field("anova.csv", A, "", "p"),   s[1, "Pr(>F)"],  tol = 5e-9)
check("v16", "ANOVA SS between", field("anova.csv", A, "", "ss_between"), s[1, "Sum Sq"],  tol = 5e-9)
check("v16", "ANOVA SS within",  field("anova.csv", A, "", "ss_within"),  s[2, "Sum Sq"],  tol = 5e-9)
check("v16", "ANOVA MS within",  field("anova.csv", A, "", "ms_within"),  s[2, "Mean Sq"], tol = 5e-9)

# D23/D76: the old schema had ONE df column, so the omnibus exported
# df=2.00 and the error df survived only if Tukey happened to be on. Both
# now have their own field, and the pair must reconstruct F(2,12).
check("v16", "ANOVA df1 exported", field("anova.csv", A, "", "df1"), s[1, "Df"], tol = 0)
check("v16", "ANOVA df2 exported", field("anova.csv", A, "", "df2"), s[2, "Df"], tol = 0)
check_true("v16", "D23/D76: both df present, so F(df1,df2) is recoverable",
           has_field("anova.csv", A, "", "df1") &&
           has_field("anova.csv", A, "", "df2"))

# --- regression: the clearest case of slot reuse (D54) ---------------------
fit <- lm(py ~ px); sm <- summary(fit); co <- coef(sm); fs <- sm$fstatistic
R <- "OLS linear regression"
check("v16", "regr slope",       field("regression.csv", R, "practice_hrs_wk", "estimate"), co["px", "Estimate"],   tol = 5e-9)
check("v16", "regr slope SE",    field("regression.csv", R, "practice_hrs_wk", "se"),       co["px", "Std. Error"], tol = 5e-9)
check("v16", "regr slope t",     field("regression.csv", R, "practice_hrs_wk", "t"),        co["px", "t value"],    tol = 5e-9)
check("v16", "regr intercept",   field("regression.csv", R, "(Intercept)", "estimate"),     co["(Intercept)", "Estimate"],   tol = 5e-9)
check("v16", "regr intercept SE",field("regression.csv", R, "(Intercept)", "se"),           co["(Intercept)", "Std. Error"], tol = 5e-9)
check("v16", "regr F",           field("regression.csv", R, "", "F"),            unname(fs["value"]), tol = 5e-9)
check("v16", "regr R-squared",   field("regression.csv", R, "", "r_squared"),    sm$r.squared,        tol = 5e-9)
check("v16", "regr adj R-squared", field("regression.csv", R, "", "adj_r_squared"), sm$adj.r.squared, tol = 5e-9)
check("v16", "regr residual SE", field("regression.csv", R, "", "residual_se"),  sm$sigma,            tol = 5e-9)

# The slope must NOT be recoverable from a field called "mean", which is
# where it used to live. This is the check that fails if the old schema
# comes back through some other route.
check_true("v16", "D54: no coefficient is written into a descriptive field",
           !has_field("regression.csv", R, "", "mean") &&
           !has_field("regression.csv", R, "", "sd") &&
           !has_field("regression.csv", R, "", "median"))

# --- correlation: D45 and the p that used to floor -------------------------
pe <- cor.test(px, py)
CT <- "Pearson correlation"; term <- "practice_hrs_wk ~ vibrato_pct"
check("v16", "Pearson r", field("correlation.csv", CT, term, "r"), unname(pe$estimate),  tol = 5e-9)
check("v16", "Pearson t", field("correlation.csv", CT, term, "t"), unname(pe$statistic), tol = 5e-9)

# The old wide file wrote this p through fixed$(p, 6), which floored
# 1.77e-16 to 0.000000 — a p of exactly zero. It now round-trips.
check("v16", "Pearson p survives export at full precision",
      field("correlation.csv", CT, term, "p"), unname(pe$p.value), tol = 1e-4)
check_true("v16", "and is not floored to zero",
           field("correlation.csv", CT, term, "p") > 0)

# --- two-group ------------------------------------------------------------
tt <- t.test(sop, alt, var.equal = FALSE)
TG <- unique(csv_of("twogroup.csv")$analysis[csv_of("twogroup.csv")$field == "t"])
check("v16", "two-group t",  field("twogroup.csv", TG, "Soprano vs Alto", "t"),  unname(tt$statistic), tol = 5e-9)
check("v16", "two-group df", field("twogroup.csv", TG, "Soprano vs Alto", "df"), unname(tt$parameter), tol = 5e-9)
check("v16", "two-group p",  field("twogroup.csv", TG, "Soprano vs Alto", "p"),  tt$p.value,           tol = 5e-9)
check("v16", "Soprano mean", field("twogroup.csv", TG, "Soprano", "mean"), mean(sop), tol = 5e-9)
check("v16", "Alto sd",      field("twogroup.csv", TG, "Alto", "sd"),      sd(alt),   tol = 5e-9)
check("v16", "Soprano n",    field("twogroup.csv", TG, "Soprano", "n"),    length(sop), tol = 0)

# Descriptives are keyed by the GROUP'S OWN NAME, not by a positional
# mean1/mean2 slot, so which group a number belongs to is in the file.
check_true("v16", "descriptives are keyed by group name, not by slot",
           has_field("twogroup.csv", TG, "Soprano", "mean") &&
           has_field("twogroup.csv", TG, "Alto", "mean"))

# --- paired: D19, a paired design has ONE n -------------------------------
pt <- t.test(pre, post, paired = TRUE)
P <- "Paired t-test"; pterm <- "jitter_pre vs jitter_post"
check("v16", "paired t",  field("paired.csv", P, pterm, "t"),  unname(pt$statistic), tol = 5e-9)
check("v16", "paired df", field("paired.csv", P, pterm, "df"), unname(pt$parameter), tol = 0)
check("v16", "paired p",  field("paired.csv", P, pterm, "p"),  pt$p.value,           tol = 5e-9)
check("v16", "paired n_pairs is written once", field("paired.csv", P, pterm, "n_pairs"), 10, tol = 0)
check_true("v16", "D19: the design is stated in the file",
           "paired" %in% csv_of("paired.csv")$value)

# --- the structural guarantees --------------------------------------------
files <- list.files(csvdir, pattern = "\\.csv$")
check_true("v16", "every export has the same six-column header",
           all(vapply(files, function(f)
               identical(names(csv_of(f)),
                         c("table", "analysis", "term", "term_type",
                           "field", "value")),
               logical(1))))

# --- term_type: the column that makes the format usable -------------------
# The first version of the long format did not have this, and pivoting the
# result produced a ragged table, because a contrast ("Soprano vs Mezzo") and
# a group ("Soprano") both live in `term`. These checks assert that the
# column exists, is never blank, uses only the documented vocabulary, and —
# the one that matters — that filtering on it yields a pivot with one row per
# term and no collisions.
allrows0 <- do.call(rbind, lapply(files, csv_of))
check_true("v16", "term_type is never blank", !any(allrows0$term_type == ""))
check_true("v16", "term_type uses only the documented vocabulary",
           all(allrows0$term_type %in%
               c("omnibus", "contrast", "group", "factor",
                 "coefficient", "error", "total", "variable")))
check_true("v16", "a term is never given two different term_types",
           !any(duplicated(unique(allrows0[, c("analysis", "term",
                                               "term_type")])[, c("analysis",
                                                                  "term")])))

# No row may be written twice. The post-hoc reporters call
# @emlCSVAddDescriptives from inside their pairwise loop, so before the
# guard a group in k contrasts had its descriptives written k times —
# identical rows, harmless read one at a time, and silently truncated by
# any pivot ("multiple rows match, first taken").
check_true("v16", "no export contains a duplicated row",
           all(vapply(files, function(f) {
               d <- csv_of(f)
               !any(duplicated(d))
           }, logical(1))))

# The point of the whole design: within one analysis and one term_type, a
# field appears at most once per term, so pivot_wider is unambiguous.
check_true("v16", "field is unique within (analysis, term_type, term)",
           !any(duplicated(allrows0[, c("table", "analysis", "term_type",
                                        "term", "field")])))

# D24, the whole point. Scan every value in every export. A zero is allowed
# only where zero is the measurement; nothing may write zero to mean "not
# applicable". The old omnibus row ended in eight of them.
allrows <- allrows0
zeros <- allrows[allrows$value == "0", ]
na_fields <- c("n", "n1", "n2", "mean", "sd", "median", "df", "df1", "df2",
               "ss", "ms", "statistic")
check_true("v16", "D24: no descriptive or df field is exported as a bare zero",
           !any(zeros$field %in% na_fields))
check_true("v16", "D24: no p is exported as a bare zero except a true zero",
           !any(zeros$field == "p" & zeros$analysis != "Spearman correlation"))

# The failure mode the long format makes impossible: a field name may mean
# exactly one thing. If "mean" ever appears on a term that is a contrast
# rather than a group, a slot is being reused again.
check_true("v16", "no descriptive field is attached to a contrast term",
           !any(allrows$field %in% c("mean", "sd", "median") &
                allrows$term_type == "contrast"))

# D66: an analysis that produces no rows must be distinguishable from a
# disk failure. The drive script asserts the reason string; here we assert
# that every committed export is non-empty, i.e. no path silently exports
# nothing.
check_true("v16", "D66: every committed export has rows",
           all(vapply(files, function(f) nrow(csv_of(f)) > 0, logical(1))))

if (!exists("EML_SUITE")) { eml_report("v16 CSV export"); eml_exit() }
