#!/usr/bin/env bash
# ============================================================================
# build_rename_inventory.sh -- the line-level census of every retired name.
#
# Ian Howell -- Embodied Music Lab -- GPL-3.0-or-later
#
# WHY THIS REPLACES A HAND-RUN GREP. The first inventory was built by a grep
# that named four extensions -- .R, .praat, .md, .txt -- and therefore captured
# the harness's generated output while missing the sixteen shell drivers that
# produce it. One of those, harness/roundtrip/run.sh:568, passes a procedure
# name as a live argument. The delegate's reconciliation caught it before any
# edit; RULING_RENAME_SCOPE_2026-09-02.md orders the census rebuilt from a
# script rather than a remembered command line.
#
# NO EXTENSION FILTER. Every file is searched. What a file's disposition is
# comes from RENAME_SCOPE.tsv, which states the scope once for every consumer.
#
#   bash walkthrough/kit/build_rename_inventory.sh > walkthrough/kit/audit/rename_call_sites.tsv
# ============================================================================
set -uo pipefail
cd "$(dirname "$0")/../.." || exit 1

SCOPE="RENAME_SCOPE.tsv"
[ -f "$SCOPE" ] || { echo "missing $SCOPE" >&2; exit 1; }

disposition_for() {
    local p="$1" pat disp
    while IFS=$'\t' read -r pat disp _; do
        case "$pat" in ''|'#'*|pattern) continue ;; esac
        case "$p" in *"$pat"*) printf '%s' "$disp"; return ;; esac
    done < "$SCOPE"
    printf 'RENAME'
}

declare -A NEW=(
 [emlRunKWAnalysis]=emlRunKruskalWallisAnalysis
 [emlRunGroupedRegression]=emlRunGroupedRegressionAnalysis
 [emlBridgeGroupComparison]=emlRunAnnotationComparison
 [emlGraphsMeltSeries]=emlReshapeSeriesLong
 [emlGraphsPivotSeries]=emlReshapeSeriesWide
 [emlInitDrawingDefaults]=emlInitializeDrawingDefaults
)

echo "# rename_call_sites.tsv -- every line holding a retired public-procedure name."
echo "# Generated by walkthrough/kit/build_rename_inventory.sh. Do not hand-edit."
echo "# Every file is searched; no extension filter. Disposition comes from"
echo "# RENAME_SCOPE.tsv: RENAME is the work, REGENERATE is rebuilt by its own"
echo "# generator, UNTOUCHED and OUT_OF_SCOPE keep their words."
printf 'old_name\tnew_name\tdisposition\tfile\tline\tline_text\n'

for old in "${!NEW[@]}"; do
    # The inventory and its generator are excluded from the SEARCH, not merely
    # labelled: this file's mapping table and the output's every row contain the
    # retired names by construction, so searching them makes the census ingest
    # itself and never settle. Labelling them out of scope is not enough --
    # a disposition says what to do with a file, not whether to read it.
    grep -rn "\b${old}\b" . --exclude-dir=.git \
        --exclude=rename_call_sites.tsv \
        --exclude=build_rename_inventory.sh 2>/dev/null | while IFS= read -r hit; do
        f="${hit%%:*}"; rest="${hit#*:}"; ln="${rest%%:*}"; txt="${rest#*:}"
        rel="${f#./}"
        printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$old" "${NEW[$old]}" "$(disposition_for "$rel")" "$rel" "$ln" \
            "$(printf '%s' "$txt" | tr '\t' ' ' | cut -c1-160)"
    done
done
