#!/usr/bin/env python3
"""The line-level census of every retired public-procedure name, classified.

Ian Howell -- Embodied Music Lab -- GPL-3.0-or-later

WHY THIS REPLACES A HAND-RUN GREP. The first inventory came from a grep naming
four extensions -- .R, .praat, .md, .txt -- so it captured the harness's
generated output and missed the sixteen shell drivers that produce it. One of
those passes a procedure name as a live argument. The delegate's reconciliation
caught it before any edit.

WHY IT ALSO CLASSIFIES. RULING_THE_OTHER_108_2026-09-02.md makes the
absence-assertion class named rather than assumed. A reference is one of these,
and only the first three rename:

  LIVE_CALL          @emlOldName invoked. Rename or it breaks at run time.
  EXPECTATION_STRING a check expecting the name in generated output. Rename
                     once the thing it inspects speaks the new name.
  DERIVED_VARIABLE   a Praat variable named after the procedure, such as
                     variableExists("emlOldName.doTukey"). Rename.
  ABSENCE_ASSERTION  a check asserting the retired name is GONE. KEEPS the
                     name; renaming it makes the check assert nothing.
  MENTION            prose or a comment. Rename for accuracy, breaks nothing.

CLASSIFICATION IS A HINT, NOT A VERDICT. The ruling requires it recorded per
file by whoever does the pass. Every row carries the rule that fired, so a
reader can disagree with a specific row rather than the whole file.

WHY ONE SCRIPT AND NOT TWO. A separate classifier was written first and
disagreed with the census: 322 rows against 818, silently dropping the known
live call in harness/dispatch/drive.praat. Two scripts walking the tree with
their own filters is the same two-copies defect this whole wave exists to
remove. Disposition is computed once, here, and classification rides with it.

  python3 walkthrough/kit/build_rename_inventory.py > walkthrough/kit/audit/rename_call_sites.tsv
"""
import os, re, subprocess

# walkthrough/kit/<this file> -> up three to the repository root.
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(REPO)

RENAMES = {
    "emlRunKWAnalysis":         "emlRunKruskalWallisAnalysis",
    "emlRunGroupedRegression":  "emlRunGroupedRegressionAnalysis",
    "emlBridgeGroupComparison": "emlRunAnnotationComparison",
    "emlGraphsMeltSeries":      "emlReshapeSeriesLong",
    "emlGraphsPivotSeries":     "emlReshapeSeriesWide",
    "emlInitDrawingDefaults":   "emlInitializeDrawingDefaults",
}

# THE CENSUS IS TAKEN AT THE REPOSITORY, NOT IN A WORKING DIRECTORY.
# Ordered 2 September (ORDER_CENSUS_INTEGRITY) after the delegate found the
# census citing 27 line numbers in walkthrough/kit/RUN_KIT_LINUX.praat, a file
# that exists in no repository: it is gitignored at walkthrough/kit/.gitignore
# line 13, generated locally, and present only in the container that built the
# census. Nothing was lost -- but a census that reads a private clone's
# untracked files describes that clone, not the repository everyone else has.
# Measured at the time: 165 untracked files contributing 1,259 rows.
#
# git ls-files IS the repository, so the universe comes from there.
def tracked_files():
    out = subprocess.run(["git", "ls-files", "-z"],
                         capture_output=True, text=True).stdout
    return set(f for f in out.split("\0") if f)

SELF = {"walkthrough/kit/audit/rename_call_sites.tsv",
        "walkthrough/kit/build_rename_inventory.py",
        "RENAME_SCOPE.tsv"}

def load_scope(path="RENAME_SCOPE.tsv"):
    rows = []
    with open(path) as fh:
        for line in fh:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2 or parts[0] == "pattern":
                continue
            rows.append((parts[0], parts[1]))
    return rows

SCOPE = load_scope()
TRACKED = tracked_files()

def disposition(path):
    for pat, disp in SCOPE:          # first match wins; unmatched is RENAME
        if pat in path:
            return disp
    return "RENAME"

ABSENCE = re.compile(
    r"appears nowhere|absent|no longer|retired|is gone|must not (appear|exist)"
    r"|not present|zero (hits|references)", re.I)

def classify(old, txt):
    if re.search(r'variableExists\s*\(\s*"%s\.' % old, txt):
        return "DERIVED_VARIABLE", 'variableExists("name.field")'
    if ABSENCE.search(txt):
        return "ABSENCE_ASSERTION", "wording asserts the name is gone"
    if re.search(r'"@?%s"' % old, txt):
        return "EXPECTATION_STRING", "name quoted as expected content"
    if re.search(r'@%s\b' % old, txt):
        return "LIVE_CALL", "@name appears in the statement"
    return "MENTION", "bare name; prose or comment"

print("# rename_call_sites.tsv -- every line holding a retired public-procedure")
print("# name, with its disposition and what the reference DOES.")
print("# Generated by walkthrough/kit/build_rename_inventory.py. Do not hand-edit.")
print("# Every file is searched; no extension filter. Disposition comes from")
print("# RENAME_SCOPE.tsv. Classification is a hint: the ruling requires it")
print("# recorded per file by whoever does the pass, and rule_fired says why.")
print("\t".join(["old_name","new_name","disposition","klass","rule_fired",
                 "file","line","line_text"]))

for old, new in RENAMES.items():
    hits = subprocess.run(["grep", "-rn", r"\b%s\b" % old, ".",
                           "--exclude-dir=.git"],
                          capture_output=True, text=True).stdout.splitlines()
    # Untracked paths are dropped below rather than here, so the count of what
    # was excluded stays measurable rather than silently absent.
    for h in hits:
        parts = h.split(":", 2)
        if len(parts) < 3:
            continue
        f, ln, txt = parts[0].lstrip("./"), parts[1], parts[2]
        if f in SELF or f not in TRACKED:
            continue
        disp = disposition(f)
        klass, why = classify(old, txt)
        print("\t".join([old, new, disp, klass, why, f, ln,
                         txt.strip()[:150].replace("\t", " ")]))
