#!/usr/bin/env python3
"""
build_table_s2.py -- generates walkthrough/kit/table_s2.tsv, the paper's
procedure table (manuscript Table S2), from plugin_EML_StatsGraphs/REGISTRY.tsv.

Run from the repo root:  python3 walkthrough/kit/build_table_s2.py
Prints the TSV to stdout. To (re)write the committed file:
    python3 walkthrough/kit/build_table_s2.py > walkthrough/kit/table_s2.tsv

WHAT THIS CLOSES
-----------------
RULING_PUBLIC_SURFACE_2026-09-01.md's mechanism item 3: "docs, the barrel,
and Table S2 are GENERATED from the registry and a text check asserts the
generated artifacts match it (single source, v105 pattern)." Before this
script, no committed generator produced Table S2 at all --
validate/v155_public_registry.R's generation check attested exactly that
gap: "Table S2 generated from REGISTRY.tsv: NOT WIRED, AND NO SUCH FILE
EXISTS." This script closes the Table S2 third of that gap.

The barrel third (plugin_EML_StatsGraphs/scripts/eml-lib-user.praat, which
setup.praat writes from its own hand-kept emlSetupModule$[] table, not from
REGISTRY.tsv) is a SEPARATE, LATER piece of work: that file sits inside
plugin_EML_StatsGraphs/, which this generator's owning task is not allowed
to touch. See planning/CLAIMS_EVIDENCE_LEDGER_2026-09-02.md row 11 and
validate/v82_generated_barrel.R (the barrel's own, unrelated, generation
check -- verifies setup.praat writes it correctly, not that it is derived
from the registry, which it still is not). The "docs" third of item 3 is
also not addressed here.

ROW COUNT IS NOT HARDCODED
---------------------------
NOTE_NAMES_ACCEPTED_2026-09-01.md: "42 public rows for 1.0 after the LMM
exclusion, and Table S2's row set is fixed." That exclusion is ORDERED
(RULING_REGISTRY_VERDICTS_2026-09-01.md #1) but has not yet EXECUTED in
REGISTRY.tsv: the mixed-model row (emlRunLMMAnalysis) still carries a row
there today, pending the pre-run settlement wave (see REGISTRY.tsv's own
header comment, and TRACKER_KIT_AND_1p0.md's "registry at 42 rows
[RULING_REGISTRY_VERDICTS #1]" line, which describes the ordered target,
not today's file). This script does not special-case that row, or any
other, and does not assert 42 or 43 anywhere: it emits one Table S2 row
per row REGISTRY.tsv actually holds when it runs. Today that is 43; once
the settlement wave's LMM exclusion lands in REGISTRY.tsv, the next run
of this script emits 42 without this file changing at all.

COLUMNS
-------
registry_name   The procedure's real name, straight from REGISTRY.tsv's
                own `name` column (see that file's own header for what
                "real" means there -- read from the procedure definition
                itself, never inferred from a call site).
kind            analysis / drawing / utility, by the SAME classify_kind()
                walkthrough/kit/build_coverage_map.py already uses for
                these same registry rows -- imported from there, not
                re-implemented, so there is one classification rule for
                the registry, not two copies that could silently drift
                apart. See that script's docstring for the exact rule.
description     REGISTRY.tsv's own one-line, curated description column,
                unchanged.

REGISTRY.tsv's `file`, `signature` and `sources` columns are its own
audit-trail and implementation-detail columns (which file defines the
procedure, its Praat parameter list, which of the ruling's three seed
sources admitted it) -- useful for maintaining the registry itself, not
for a reader of the paper's procedure table, so they are left out of
Table S2 here. This three-column shape is an editorial choice, not a
ruling: it has not been put to Ian, and nothing about the generation
mechanism changes if a reviewer asks for the two extra columns back.

ATTRIBUTION
Framework: EML PraatGen by Ian Howell
           Embodied Music Lab -- www.embodiedmusiclab.com
Code generation: Claude (Anthropic)
Script author: Ian Howell -- created and verified by this individual
"""
import os
import sys

# Import, not re-implement: build_coverage_map.py already reads
# REGISTRY.tsv rows and classifies each one's kind for the identical
# purpose (a per-registry-row derived table). Python puts the running
# script's own directory on sys.path automatically, but the insert below
# is explicit rather than relying on that default, so this still resolves
# if the caller invokes it in some way that does not set sys.path[0].
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_coverage_map as bcm  # noqa: E402  (path insert must precede)

REGISTRY_PATH = os.path.join("plugin_EML_StatsGraphs", "REGISTRY.tsv")


def main():
    registry_rows = bcm.read_registry_rows(REGISTRY_PATH)

    out = []
    out.append(
        "# table_s2.tsv -- generated by walkthrough/kit/build_table_s2.py"
    )
    out.append(
        "# DO NOT HAND-EDIT. Regenerate with:"
        " python3 walkthrough/kit/build_table_s2.py > walkthrough/kit/table_s2.tsv"
    )
    out.append(
        "# The paper's procedure table (manuscript Table S2), one row per"
        " plugin_EML_StatsGraphs/REGISTRY.tsv row. The row count is"
        " whatever the registry currently holds -- not asserted here; see"
        " this script's own docstring (43 rows while the mixed-model row"
        " awaits the settlement wave's ordered exclusion, 42 once that"
        " exclusion executes in REGISTRY.tsv)."
    )
    out.append("registry_name\tkind\tdescription")

    for row in registry_rows:
        name = row["name"]
        description = row["description"]
        kind = bcm.classify_kind(name, description)
        out.append("\t".join([name, kind, description]))

    sys.stdout.write("\n".join(out) + "\n")
    sys.stderr.write(
        "build_table_s2.py: %d REGISTRY.tsv rows -> %d Table S2 rows\n"
        % (len(registry_rows), len(registry_rows))
    )


if __name__ == "__main__":
    main()
