# forest_plot.R -- the agreement forest plot for the paper.
#
# Reads the kit's own comparison output (results/agreement_by_procedure.tsv,
# generated by compare.R) and draws one forest-plot row per
# (procedure, post-hoc arm, study): the observed agreement rate as a point,
# a 95% Wilson score interval as a horizontal whisker, point area scaled to
# the number of quantities compared. Panels split by study (options, sweep)
# -- Tier B, the standard-agreement-rule universe (ACCEPTANCE_RULES.md,
# section 1 and section 6). The NIST study is scored by log-relative-error
# against a certified constant, not by an agreement proportion, and is
# deliberately NOT forced into this plot -- see the header note under
# "NIST AND THIS PLOT" below and the loud flag in
# mailbox/to-fable/REPORT_ACCEPTANCE_AND_FOREST_2026-09-02.md.
#
# It needs no package -- same discipline as compare.R.
#
# USAGE
#   Rscript forest_plot.R
#   (or `source("forest_plot.R")` from an R session with the working
#   directory anywhere; it locates itself the same way compare.R does.)
#
# INPUT, IN PRIORITY ORDER
#   1. walkthrough/kit/results/agreement_by_procedure.tsv, if present and
#      it parses -- this is compare.R's own generated per-procedure
#      summary, i.e. "the kit's comparison output" this script is asked to
#      read. Real data if the kit has ever been run and compare.R's
#      GENERATION step reached completion.
#   2. Otherwise, SYNTHETIC DATA generated by this script itself, in the
#      identical column shape, clearly labeled as synthetic in the console
#      output, in the file this script writes, and directly on the plot
#      (a banner at the top of the image, and "SYNTHETIC DATA" appended to
#      the title). This keeps the script runnable end to end -- Job
#      requirement -- without ever letting a synthetic run pass silently
#      as a real one.
#
# OUTPUT
#   walkthrough/kit/results/forest_plot_agreement.png
#
# NIST AND THIS PLOT (OPEN, flagged loudly rather than decided quietly)
#   ACCEPTANCE_RULES.md sections 1, 3 and 7 score NIST cells by LRE against
#   a published constant, never by a Praat-vs-R agreement proportion --
#   there is no "percent agreement" number for a NIST cell the way there is
#   for a Tier B one, and results/agreement_by_procedure.tsv's own NIST
#   rows currently read quantities_compared=0, percent_agreement="n/a"
#   (compare.R splits the NIST cells out of the P/R contract machinery
#   before that table is built -- see compare.R's own comment on Pnist/
#   Rnist). Forcing NIST into a percent-agreement forest-plot row would
#   misrepresent what was actually measured there. This script therefore
#   PLOTS TIER B ONLY and reports the NIST row count it excluded, by name,
#   in its own console output -- so the exclusion is visible, not silent.
#   Whether the paper wants a SEPARATE NIST panel (e.g. digit margin over
#   the certified floor, per quantity) is not decided by any ruling read
#   for this job and is flagged to Fable rather than invented here.

emlThisFile <- function() {
    args <- commandArgs(trailingOnly = FALSE)
    fileArg <- sub("^--file=", "", args[grepl("^--file=", args)])
    if (length(fileArg)) return(normalizePath(fileArg))
    for (i in rev(seq_along(sys.frames()))) {
        ofile <- sys.frames()[[i]]$ofile
        if (!is.null(ofile)) return(normalizePath(ofile))
    }
    if (requireNamespace("rstudioapi", quietly = TRUE) &&
        isTRUE(tryCatch(rstudioapi::isAvailable(), error = function(e) FALSE))) {
        ctx <- tryCatch(rstudioapi::getSourceEditorContext(), error = function(e) NULL)
        if (!is.null(ctx) && nzchar(ctx$path)) return(normalizePath(ctx$path))
    }
    stop("forest_plot.R can't find its own location.\nIn RStudio: Session > Set ",
         "Working Directory > To Source File Location, then Source again.",
         call. = FALSE)
}
kitDir <- dirname(emlThisFile())
resultsDir <- file.path(kitDir, "results")
dir.create(resultsDir, showWarnings = FALSE)

# --- Wilson score interval for a binomial proportion, base R, no package ---
# Preferred over the Wald interval for a rate that can sit at or near 100%
# (agreement rates commonly do): Wald collapses to a zero-width interval at
# p=1, which reads as false certainty. Wilson does not.
wilsonCI <- function(x, n, conf = 0.95) {
    if (n <= 0 || is.na(x) || is.na(n)) return(c(low = NA_real_, high = NA_real_))
    p <- x / n
    z <- qnorm(1 - (1 - conf) / 2)
    denom <- 1 + z^2 / n
    centre <- p + z^2 / (2 * n)
    half <- z * sqrt((p * (1 - p) + z^2 / (4 * n)) / n)
    c(low = max(0, (centre - half) / denom), high = min(1, (centre + half) / denom))
}

# --- 1. TRY THE REAL COMPARISON OUTPUT ---------------------------------
abpPath <- file.path(resultsDir, "agreement_by_procedure.tsv")
isSynthetic <- FALSE
AGP <- NULL
if (file.exists(abpPath)) {
    AGP <- tryCatch(
        read.delim(abpPath, sep = "\t", colClasses = "character", quote = "", comment.char = ""),
        error = function(e) NULL)
    needCols <- c("procedure", "post_hoc", "quantities_compared", "agreeing", "study")
    if (is.null(AGP) || !all(needCols %in% names(AGP)) || nrow(AGP) == 0) {
        cat(sprintf("*** %s exists but did not parse into the expected shape -- falling back to synthetic data.\n", abpPath))
        AGP <- NULL
    }
}

# --- 2. SYNTHETIC FALLBACK, CLEARLY LABELED -----------------------------
if (is.null(AGP)) {
    isSynthetic <- TRUE
    cat("\n*** NO USABLE walkthrough/kit/results/agreement_by_procedure.tsv FOUND.\n")
    cat("*** Generating SYNTHETIC data in the same column shape so this script still runs\n")
    cat("*** to completion. This is NOT a measurement of the plugin. Do not cite it.\n\n")
    set.seed(20260902L)  # reproducible synthetic run, not a measurement seed
    synthProcs <- c("Two Group Analysis", "Anova Analysis", "KW Analysis",
                     "Correlation Analysis", "Regression Analysis",
                     "Repeated Measures Analysis", "Friedman Analysis",
                     "Two Way Analysis", "Cronbach Alpha", "Chi Square Independence")
    rows <- list()
    for (proc in synthProcs) {
        for (study in c("options", "sweep")) {
            n <- sample(30:400, 1)
            # Nearly all agree, with one procedure (Two Way Analysis) seeded
            # with a visibly lower rate, so a reader of the synthetic plot
            # can tell rows apart -- a plot where every point sits at 100%
            # would not exercise the whisker geometry at all.
            rate <- if (proc == "Two Way Analysis") 0.85 else runif(1, 0.985, 1.0)
            agreeing <- rbinom(1, n, rate)
            rows[[length(rows) + 1]] <- data.frame(
                procedure = proc, post_hoc = "", quantities_compared = as.character(n),
                agreeing = as.character(agreeing), differing_documented = "0",
                one_sided_documented = "0",
                percent_agreement_of_compared = sprintf("%.2f%%", 100 * agreeing / n),
                study = study, stringsAsFactors = FALSE)
        }
    }
    AGP <- do.call(rbind, rows)
    write.table(AGP, file.path(resultsDir, "SYNTHETIC_agreement_by_procedure.tsv"),
                sep = "\t", quote = FALSE, row.names = FALSE)
    cat(sprintf("*** Synthetic input written to %s for inspection.\n\n",
                file.path(resultsDir, "SYNTHETIC_agreement_by_procedure.tsv")))
}

# --- 3. TIER B ONLY: DROP NIST, REPORT WHAT WAS EXCLUDED ----------------
AGP$quantities_compared <- suppressWarnings(as.numeric(AGP$quantities_compared))
AGP$agreeing             <- suppressWarnings(as.numeric(AGP$agreeing))
nistRows <- AGP[AGP$study == "nist", , drop = FALSE]
if (nrow(nistRows))
    cat(sprintf("*** Excluding %d nist-study row(s) from the forest plot -- NIST is scored by LRE, not agreement rate. See this file's header.\n",
                nrow(nistRows)))
TB <- AGP[AGP$study %in% c("options", "sweep") & !is.na(AGP$quantities_compared) &
          AGP$quantities_compared > 0, , drop = FALSE]
if (!nrow(TB)) stop("forest_plot.R: no Tier B (options/sweep) rows with quantities_compared > 0 -- nothing to plot.", call. = FALSE)

# One row per (procedure, post_hoc, study); label carries post_hoc when set,
# since agreement_by_procedure.tsv already splits some procedures by
# post-hoc arm (e.g. "Anova Analysis" appears at post_hoc="", "0" and "1").
TB$label <- ifelse(nzchar(TB$post_hoc), paste0(TB$procedure, " [", TB$post_hoc, "]"), TB$procedure)
TB$rate  <- TB$agreeing / TB$quantities_compared
ci <- t(mapply(wilsonCI, TB$agreeing, TB$quantities_compared))
TB$ci_low <- ci[, "low"]; TB$ci_high <- ci[, "high"]

# Sort within each study panel by rate ascending (worst at top when plotted
# top-to-bottom via decreasing y), so the eye finds the exceptions first.
TB <- TB[order(TB$study, TB$rate), ]

# --- 4. DRAW ---------------------------------------------------------------
outPath <- file.path(resultsDir, "forest_plot_agreement.png")
studies <- intersect(c("options", "sweep"), unique(TB$study))
nStudies <- length(studies)
maxRows <- max(tapply(TB$label, TB$study, length))
imgHeight <- max(480, 90 + 26 * maxRows)
png(outPath, width = 1500, height = imgHeight * nStudies + 160, res = 150)
op <- par(mfrow = c(nStudies, 1), mar = c(4, 15, 3, 6), oma = c(0, 0, isSynthetic * 2 + 3, 0))
for (study in studies) {
    d <- TB[TB$study == study, , drop = FALSE]
    n <- nrow(d)
    ypos <- seq_len(n)
    plot(NA, xlim = c(min(0.5, min(d$ci_low, na.rm = TRUE) - 0.02), 1.14), ylim = c(0.5, n + 0.5),
         yaxt = "n", xlab = "Agreement rate (Wilson 95% CI)",
         ylab = "", main = sprintf("Tier B agreement by procedure -- study: %s%s",
                                    study, if (isSynthetic) "  [SYNTHETIC DATA]" else ""),
         bty = "n")
    abline(v = 1.0, col = "grey60", lty = 2)
    axis(2, at = ypos, labels = d$label, las = 2, cex.axis = 0.75)
    segments(d$ci_low, ypos, d$ci_high, ypos, col = "steelblue4", lwd = 2)
    ptCex <- 0.6 + 1.4 * (d$quantities_compared / max(TB$quantities_compared))
    points(d$rate, ypos, pch = 21, bg = "steelblue2", col = "steelblue4", cex = ptCex)
    text(d$ci_high, ypos, sprintf(" n=%d", d$quantities_compared), pos = 4, cex = 0.6, col = "grey30")
}
if (isSynthetic) {
    mtext("SYNTHETIC DATA -- no real comparison output was found; this plot exercises the script only and must not be cited.",
          outer = TRUE, side = 3, line = 0.5, cex = 0.85, col = "firebrick", font = 2)
}
par(op)
dev.off()

cat(sprintf("\nWrote %s\n", outPath))
cat(sprintf("Rows plotted: %d, across %d study panel(s) (%s).\n", nrow(TB), nStudies, paste(studies, collapse = ", ")))
if (isSynthetic) {
    cat("*** REMINDER: the input to this run was SYNTHETIC. Re-run after the authoritative\n")
    cat("*** run to get the real plot; do not use this image in the paper.\n")
}
invisible(NULL)
